# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeDrawingPage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DrawingPageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeDrawingPage", llm_response=llm_response, mode="request")
        return typing.cast(types.DrawingPageAnalysis, __result__)

    def AnalyzePage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePage", llm_response=llm_response, mode="request")
        return typing.cast(types.PageAnalysis, __result__)

    def CheckRelevance(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RelevanceJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CheckRelevance", llm_response=llm_response, mode="request")
        return typing.cast(types.RelevanceJudgment, __result__)

    def ExtractEntitiesFromText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEntitiesFromText", llm_response=llm_response, mode="request")
        return typing.cast(types.PageAnalysis, __result__)

    def GenerateSyntheticQueries(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SyntheticQueries:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateSyntheticQueries", llm_response=llm_response, mode="request")
        return typing.cast(types.SyntheticQueries, __result__)

    def JudgeAnswerQuality(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AnswerQualityJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeAnswerQuality", llm_response=llm_response, mode="request")
        return typing.cast(types.AnswerQualityJudgment, __result__)

    def SynthesizeDocument(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DocumentSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeDocument", llm_response=llm_response, mode="request")
        return typing.cast(types.DocumentSynthesis, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeDrawingPage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DrawingPageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeDrawingPage", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DrawingPageAnalysis, __result__)

    def AnalyzePage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePage", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PageAnalysis, __result__)

    def CheckRelevance(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RelevanceJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CheckRelevance", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RelevanceJudgment, __result__)

    def ExtractEntitiesFromText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEntitiesFromText", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PageAnalysis, __result__)

    def GenerateSyntheticQueries(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SyntheticQueries:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateSyntheticQueries", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SyntheticQueries, __result__)

    def JudgeAnswerQuality(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AnswerQualityJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeAnswerQuality", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AnswerQualityJudgment, __result__)

    def SynthesizeDocument(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DocumentSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeDocument", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DocumentSynthesis, __result__)

    