# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (14)
# #########################################################################

class AnswerQualityJudgment(BaseModel):
    score: float = Field(description='Answer quality score from 0.0 (completely wrong) to 1.0 (perfect)')
    reasoning: str = Field(description='Brief explanation of the score')

class DetectedComponent(BaseModel):
    component_id: str = Field(description='stable within-page ID: \'R1\', \'V-101\', or synthesised')
    symbol_class: str = Field(description='resistor | capacitor | valve | pump | junction | off_page_connector | ...')
    label: typing.Optional[str] = Field(default=None, description='visible printed text near the symbol')
    bbox: typing.List[int] = Field(description='[x, y, w, h] page pixel coords')
    ports: typing.List["Port"]
    properties: typing.Optional[typing.Dict[str, str]] = None

class DetectedConnection(BaseModel):
    from_component: str
    from_port: typing.Optional[str] = None
    to_component: str
    to_port: typing.Optional[str] = None
    net_label: typing.Optional[str] = Field(default=None, description='\'N5\', \'+24V\', or null for unnamed')
    wire_style: typing.Optional[str] = Field(default=None, description='solid | dashed | pneumatic | hydraulic | signal')

class DiscoveredEntity(BaseModel):
    name: str
    category: str
    value: typing.Optional[str] = None
    context: str

class DiscoveredTable(BaseModel):
    title: typing.Optional[str] = None
    columns: typing.List[str]
    rows: typing.List[typing.Dict[str, str]]

class DocumentSynthesis(BaseModel):
    cross_references: typing.List["SynthesisCrossReference"]
    page_clusters: typing.List["SynthesisPageCluster"]
    document_summary: str

class DrawingPageAnalysis(BaseModel):
    page_number: int
    sheet_number: typing.Optional[str] = None
    zone_grid: typing.Optional[str] = Field(default=None, description='\'A-H horizontal, 1-8 vertical\' or similar grid spec')
    domain: str = Field(description='electrical | p_and_id | mechanical | mixed')
    components: typing.List["DetectedComponent"]
    connections: typing.List["DetectedConnection"]
    off_page_connectors: typing.List["OffPageConnector"]
    title_block: typing.Optional[typing.Dict[str, str]] = None
    notes: typing.List[str]
    page_type: str = Field(description='drawing | title_page | bom | text | mixed')

class OffPageConnector(BaseModel):
    tag: str = Field(description='\'/A2\', \'OPC-1\', \'to sheet 3 zone B2\'')
    bound_component: str = Field(description='on-page component_id it terminates at')
    target_hint: typing.Optional[str] = Field(default=None, description='parsed \'sheet 3, zone B2\' hint if present')

class PageAnalysis(BaseModel):
    description: str
    entities: typing.List["DiscoveredEntity"]
    tables: typing.List["DiscoveredTable"]
    annotations: typing.List[str]
    page_type: str

class Port(BaseModel):
    port_id: str = Field(description='label or index of the port')
    position: typing.Optional[typing.List[int]] = Field(default=None, description='[x, y] in page pixel coords, optional')

class RelevanceJudgment(BaseModel):
    relevant: bool
    reasoning: str
    needs_clarification: bool
    clarifying_question: typing.Optional[str] = None
    clarifying_options: typing.Optional[typing.List[str]] = None

class SynthesisCrossReference(BaseModel):
    source_page: int
    target_page: int
    relationship: str
    shared_entities: typing.List[str]

class SynthesisPageCluster(BaseModel):
    pages: typing.List[int]
    reason: str

class SyntheticQueries(BaseModel):
    queries: typing.List[str] = Field(description='Short questions the passage directly answers, one per facet.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
