# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def AnalyzePage(self, page_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.PageAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AnalyzePage(page_image=page_image,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AnalyzePage", args={
                "page_image": page_image,
            })
            return typing.cast(types.PageAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def AnalyzeQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.QueryAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AnalyzeQuery(query=query,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AnalyzeQuery", args={
                "query": query,
            })
            return typing.cast(types.QueryAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def CheckRelevance(self, query: str,passage: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RelevanceJudgment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CheckRelevance(query=query,passage=passage,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CheckRelevance", args={
                "query": query,"passage": passage,
            })
            return typing.cast(types.RelevanceJudgment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def CompressRetrievedContext(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CompressedContext:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CompressRetrievedContext(query=query,passages=passages,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CompressRetrievedContext", args={
                "query": query,"passages": passages,
            })
            return typing.cast(types.CompressedContext, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ContinueDocumentStructure(self, existing_structure: str,pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ExtractedStructure:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ContinueDocumentStructure(existing_structure=existing_structure,pages_text=pages_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ContinueDocumentStructure", args={
                "existing_structure": existing_structure,"pages_text": pages_text,
            })
            return typing.cast(types.ExtractedStructure, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DetectTableOfContents(self, page_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TocDetectionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DetectTableOfContents(page_text=page_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DetectTableOfContents", args={
                "page_text": page_text,
            })
            return typing.cast(types.TocDetectionResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractDocumentStructure(self, pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ExtractedStructure:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractDocumentStructure(pages_text=pages_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractDocumentStructure", args={
                "pages_text": pages_text,
            })
            return typing.cast(types.ExtractedStructure, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractEntitiesFromText(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PageAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractEntitiesFromText(text=text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractEntitiesFromText", args={
                "text": text,
            })
            return typing.cast(types.PageAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def FindSectionStart(self, section_title: str,pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> int:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.FindSectionStart(section_title=section_title,pages_text=pages_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="FindSectionStart", args={
                "section_title": section_title,"pages_text": pages_text,
            })
            return typing.cast(int, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateAnswer(self, system_prompt: str,context: str,query: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateAnswer(system_prompt=system_prompt,context=context,query=query,history=history,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateAnswer", args={
                "system_prompt": system_prompt,"context": context,"query": query,"history": history,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateDocDescription(self, tree_structure: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateDocDescription(tree_structure=tree_structure,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateDocDescription", args={
                "tree_structure": tree_structure,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateHypotheticalDocument(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.HypotheticalDocument:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateHypotheticalDocument(query=query,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateHypotheticalDocument", args={
                "query": query,
            })
            return typing.cast(types.HypotheticalDocument, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateNodeSummary(self, title: str,section_text: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateNodeSummary(title=title,section_text=section_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateNodeSummary", args={
                "title": title,"section_text": section_text,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateQueryVariants(self, query: str,num_variants: int,
        baml_options: BamlCallOptions = {},
    ) -> types.QueryVariants:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateQueryVariants(query=query,num_variants=num_variants,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateQueryVariants", args={
                "query": query,"num_variants": num_variants,
            })
            return typing.cast(types.QueryVariants, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateReasoningStep(self, query: str,context: str,prior_reasoning: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ReasoningStep:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateReasoningStep(query=query,context=context,prior_reasoning=prior_reasoning,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateReasoningStep", args={
                "query": query,"context": context,"prior_reasoning": prior_reasoning,
            })
            return typing.cast(types.ReasoningStep, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateStepBackQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.StepBackQuery:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateStepBackQuery(query=query,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateStepBackQuery", args={
                "query": query,
            })
            return typing.cast(types.StepBackQuery, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def JudgeAnswerQuality(self, query: str,prediction: str,reference: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AnswerQualityJudgment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.JudgeAnswerQuality(query=query,prediction=prediction,reference=reference,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="JudgeAnswerQuality", args={
                "query": query,"prediction": prediction,"reference": reference,
            })
            return typing.cast(types.AnswerQualityJudgment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def JudgeRetrievalNecessity(self, query: str,knowledge_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RetrievalNecessityJudgment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.JudgeRetrievalNecessity(query=query,knowledge_description=knowledge_description,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="JudgeRetrievalNecessity", args={
                "query": query,"knowledge_description": knowledge_description,
            })
            return typing.cast(types.RetrievalNecessityJudgment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ParseTableOfContents(self, toc_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TocStructure:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ParseTableOfContents(toc_text=toc_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ParseTableOfContents", args={
                "toc_text": toc_text,
            })
            return typing.cast(types.TocStructure, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def RerankChunks(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.RankedChunk"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.RerankChunks(query=query,passages=passages,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="RerankChunks", args={
                "query": query,"passages": passages,
            })
            return typing.cast(typing.List["types.RankedChunk"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SynthesizeDocument(self, page_analyses: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DocumentSynthesis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SynthesizeDocument(page_analyses=page_analyses,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SynthesizeDocument", args={
                "page_analyses": page_analyses,
            })
            return typing.cast(types.DocumentSynthesis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def TreeRetrievalStep(self, query: str,tree_structure: str,accumulated_context: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ToolFetchPages", "types.ToolDrillDown", "types.ToolResolvedPages"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.TreeRetrievalStep(query=query,tree_structure=tree_structure,accumulated_context=accumulated_context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="TreeRetrievalStep", args={
                "query": query,"tree_structure": tree_structure,"accumulated_context": accumulated_context,
            })
            return typing.cast(typing.Union["types.ToolFetchPages", "types.ToolDrillDown", "types.ToolResolvedPages"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def VerifySectionPosition(self, title: str,page_text: str,
        baml_options: BamlCallOptions = {},
    ) -> bool:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.VerifySectionPosition(title=title,page_text=page_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="VerifySectionPosition", args={
                "title": title,"page_text": page_text,
            })
            return typing.cast(bool, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzePage(self, page_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PageAnalysis, types.PageAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AnalyzePage", args={
            "page_image": page_image,
        })
        return baml_py.BamlStream[stream_types.PageAnalysis, types.PageAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.PageAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PageAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def AnalyzeQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.QueryAnalysis, types.QueryAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AnalyzeQuery", args={
            "query": query,
        })
        return baml_py.BamlStream[stream_types.QueryAnalysis, types.QueryAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.QueryAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QueryAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CheckRelevance(self, query: str,passage: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.RelevanceJudgment, types.RelevanceJudgment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CheckRelevance", args={
            "query": query,"passage": passage,
        })
        return baml_py.BamlStream[stream_types.RelevanceJudgment, types.RelevanceJudgment](
          __result__,
          lambda x: typing.cast(stream_types.RelevanceJudgment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RelevanceJudgment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CompressRetrievedContext(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CompressedContext, types.CompressedContext]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CompressRetrievedContext", args={
            "query": query,"passages": passages,
        })
        return baml_py.BamlStream[stream_types.CompressedContext, types.CompressedContext](
          __result__,
          lambda x: typing.cast(stream_types.CompressedContext, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CompressedContext, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ContinueDocumentStructure(self, existing_structure: str,pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ExtractedStructure, types.ExtractedStructure]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ContinueDocumentStructure", args={
            "existing_structure": existing_structure,"pages_text": pages_text,
        })
        return baml_py.BamlStream[stream_types.ExtractedStructure, types.ExtractedStructure](
          __result__,
          lambda x: typing.cast(stream_types.ExtractedStructure, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ExtractedStructure, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DetectTableOfContents(self, page_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.TocDetectionResult, types.TocDetectionResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DetectTableOfContents", args={
            "page_text": page_text,
        })
        return baml_py.BamlStream[stream_types.TocDetectionResult, types.TocDetectionResult](
          __result__,
          lambda x: typing.cast(stream_types.TocDetectionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TocDetectionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractDocumentStructure(self, pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ExtractedStructure, types.ExtractedStructure]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractDocumentStructure", args={
            "pages_text": pages_text,
        })
        return baml_py.BamlStream[stream_types.ExtractedStructure, types.ExtractedStructure](
          __result__,
          lambda x: typing.cast(stream_types.ExtractedStructure, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ExtractedStructure, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractEntitiesFromText(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PageAnalysis, types.PageAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractEntitiesFromText", args={
            "text": text,
        })
        return baml_py.BamlStream[stream_types.PageAnalysis, types.PageAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.PageAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PageAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def FindSectionStart(self, section_title: str,pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[int, int]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="FindSectionStart", args={
            "section_title": section_title,"pages_text": pages_text,
        })
        return baml_py.BamlStream[int, int](
          __result__,
          lambda x: typing.cast(int, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(int, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateAnswer(self, system_prompt: str,context: str,query: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateAnswer", args={
            "system_prompt": system_prompt,"context": context,"query": query,"history": history,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateDocDescription(self, tree_structure: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateDocDescription", args={
            "tree_structure": tree_structure,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateHypotheticalDocument(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.HypotheticalDocument, types.HypotheticalDocument]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateHypotheticalDocument", args={
            "query": query,
        })
        return baml_py.BamlStream[stream_types.HypotheticalDocument, types.HypotheticalDocument](
          __result__,
          lambda x: typing.cast(stream_types.HypotheticalDocument, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.HypotheticalDocument, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateNodeSummary(self, title: str,section_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateNodeSummary", args={
            "title": title,"section_text": section_text,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateQueryVariants(self, query: str,num_variants: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.QueryVariants, types.QueryVariants]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateQueryVariants", args={
            "query": query,"num_variants": num_variants,
        })
        return baml_py.BamlStream[stream_types.QueryVariants, types.QueryVariants](
          __result__,
          lambda x: typing.cast(stream_types.QueryVariants, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QueryVariants, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateReasoningStep(self, query: str,context: str,prior_reasoning: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ReasoningStep, types.ReasoningStep]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateReasoningStep", args={
            "query": query,"context": context,"prior_reasoning": prior_reasoning,
        })
        return baml_py.BamlStream[stream_types.ReasoningStep, types.ReasoningStep](
          __result__,
          lambda x: typing.cast(stream_types.ReasoningStep, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ReasoningStep, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateStepBackQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.StepBackQuery, types.StepBackQuery]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateStepBackQuery", args={
            "query": query,
        })
        return baml_py.BamlStream[stream_types.StepBackQuery, types.StepBackQuery](
          __result__,
          lambda x: typing.cast(stream_types.StepBackQuery, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.StepBackQuery, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def JudgeAnswerQuality(self, query: str,prediction: str,reference: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AnswerQualityJudgment, types.AnswerQualityJudgment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="JudgeAnswerQuality", args={
            "query": query,"prediction": prediction,"reference": reference,
        })
        return baml_py.BamlStream[stream_types.AnswerQualityJudgment, types.AnswerQualityJudgment](
          __result__,
          lambda x: typing.cast(stream_types.AnswerQualityJudgment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AnswerQualityJudgment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def JudgeRetrievalNecessity(self, query: str,knowledge_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.RetrievalNecessityJudgment, types.RetrievalNecessityJudgment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="JudgeRetrievalNecessity", args={
            "query": query,"knowledge_description": knowledge_description,
        })
        return baml_py.BamlStream[stream_types.RetrievalNecessityJudgment, types.RetrievalNecessityJudgment](
          __result__,
          lambda x: typing.cast(stream_types.RetrievalNecessityJudgment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RetrievalNecessityJudgment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ParseTableOfContents(self, toc_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.TocStructure, types.TocStructure]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ParseTableOfContents", args={
            "toc_text": toc_text,
        })
        return baml_py.BamlStream[stream_types.TocStructure, types.TocStructure](
          __result__,
          lambda x: typing.cast(stream_types.TocStructure, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TocStructure, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RerankChunks(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.List["stream_types.RankedChunk"], typing.List["types.RankedChunk"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="RerankChunks", args={
            "query": query,"passages": passages,
        })
        return baml_py.BamlStream[typing.List["stream_types.RankedChunk"], typing.List["types.RankedChunk"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.RankedChunk"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.RankedChunk"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeDocument(self, page_analyses: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DocumentSynthesis, types.DocumentSynthesis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SynthesizeDocument", args={
            "page_analyses": page_analyses,
        })
        return baml_py.BamlStream[stream_types.DocumentSynthesis, types.DocumentSynthesis](
          __result__,
          lambda x: typing.cast(stream_types.DocumentSynthesis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DocumentSynthesis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def TreeRetrievalStep(self, query: str,tree_structure: str,accumulated_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.ToolFetchPages", "stream_types.ToolDrillDown", "stream_types.ToolResolvedPages"], typing.Union["types.ToolFetchPages", "types.ToolDrillDown", "types.ToolResolvedPages"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="TreeRetrievalStep", args={
            "query": query,"tree_structure": tree_structure,"accumulated_context": accumulated_context,
        })
        return baml_py.BamlStream[typing.Union["stream_types.ToolFetchPages", "stream_types.ToolDrillDown", "stream_types.ToolResolvedPages"], typing.Union["types.ToolFetchPages", "types.ToolDrillDown", "types.ToolResolvedPages"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.ToolFetchPages", "stream_types.ToolDrillDown", "stream_types.ToolResolvedPages"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.ToolFetchPages", "types.ToolDrillDown", "types.ToolResolvedPages"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def VerifySectionPosition(self, title: str,page_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[bool, bool]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="VerifySectionPosition", args={
            "title": title,"page_text": page_text,
        })
        return baml_py.BamlStream[bool, bool](
          __result__,
          lambda x: typing.cast(bool, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(bool, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnalyzePage(self, page_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzePage", args={
            "page_image": page_image,
        }, mode="request")
        return __result__
    async def AnalyzeQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeQuery", args={
            "query": query,
        }, mode="request")
        return __result__
    async def CheckRelevance(self, query: str,passage: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CheckRelevance", args={
            "query": query,"passage": passage,
        }, mode="request")
        return __result__
    async def CompressRetrievedContext(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CompressRetrievedContext", args={
            "query": query,"passages": passages,
        }, mode="request")
        return __result__
    async def ContinueDocumentStructure(self, existing_structure: str,pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ContinueDocumentStructure", args={
            "existing_structure": existing_structure,"pages_text": pages_text,
        }, mode="request")
        return __result__
    async def DetectTableOfContents(self, page_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectTableOfContents", args={
            "page_text": page_text,
        }, mode="request")
        return __result__
    async def ExtractDocumentStructure(self, pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractDocumentStructure", args={
            "pages_text": pages_text,
        }, mode="request")
        return __result__
    async def ExtractEntitiesFromText(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractEntitiesFromText", args={
            "text": text,
        }, mode="request")
        return __result__
    async def FindSectionStart(self, section_title: str,pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FindSectionStart", args={
            "section_title": section_title,"pages_text": pages_text,
        }, mode="request")
        return __result__
    async def GenerateAnswer(self, system_prompt: str,context: str,query: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateAnswer", args={
            "system_prompt": system_prompt,"context": context,"query": query,"history": history,
        }, mode="request")
        return __result__
    async def GenerateDocDescription(self, tree_structure: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateDocDescription", args={
            "tree_structure": tree_structure,
        }, mode="request")
        return __result__
    async def GenerateHypotheticalDocument(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateHypotheticalDocument", args={
            "query": query,
        }, mode="request")
        return __result__
    async def GenerateNodeSummary(self, title: str,section_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateNodeSummary", args={
            "title": title,"section_text": section_text,
        }, mode="request")
        return __result__
    async def GenerateQueryVariants(self, query: str,num_variants: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateQueryVariants", args={
            "query": query,"num_variants": num_variants,
        }, mode="request")
        return __result__
    async def GenerateReasoningStep(self, query: str,context: str,prior_reasoning: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateReasoningStep", args={
            "query": query,"context": context,"prior_reasoning": prior_reasoning,
        }, mode="request")
        return __result__
    async def GenerateStepBackQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateStepBackQuery", args={
            "query": query,
        }, mode="request")
        return __result__
    async def JudgeAnswerQuality(self, query: str,prediction: str,reference: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="JudgeAnswerQuality", args={
            "query": query,"prediction": prediction,"reference": reference,
        }, mode="request")
        return __result__
    async def JudgeRetrievalNecessity(self, query: str,knowledge_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="JudgeRetrievalNecessity", args={
            "query": query,"knowledge_description": knowledge_description,
        }, mode="request")
        return __result__
    async def ParseTableOfContents(self, toc_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ParseTableOfContents", args={
            "toc_text": toc_text,
        }, mode="request")
        return __result__
    async def RerankChunks(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RerankChunks", args={
            "query": query,"passages": passages,
        }, mode="request")
        return __result__
    async def SynthesizeDocument(self, page_analyses: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SynthesizeDocument", args={
            "page_analyses": page_analyses,
        }, mode="request")
        return __result__
    async def TreeRetrievalStep(self, query: str,tree_structure: str,accumulated_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="TreeRetrievalStep", args={
            "query": query,"tree_structure": tree_structure,"accumulated_context": accumulated_context,
        }, mode="request")
        return __result__
    async def VerifySectionPosition(self, title: str,page_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="VerifySectionPosition", args={
            "title": title,"page_text": page_text,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnalyzePage(self, page_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzePage", args={
            "page_image": page_image,
        }, mode="stream")
        return __result__
    async def AnalyzeQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeQuery", args={
            "query": query,
        }, mode="stream")
        return __result__
    async def CheckRelevance(self, query: str,passage: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CheckRelevance", args={
            "query": query,"passage": passage,
        }, mode="stream")
        return __result__
    async def CompressRetrievedContext(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CompressRetrievedContext", args={
            "query": query,"passages": passages,
        }, mode="stream")
        return __result__
    async def ContinueDocumentStructure(self, existing_structure: str,pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ContinueDocumentStructure", args={
            "existing_structure": existing_structure,"pages_text": pages_text,
        }, mode="stream")
        return __result__
    async def DetectTableOfContents(self, page_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DetectTableOfContents", args={
            "page_text": page_text,
        }, mode="stream")
        return __result__
    async def ExtractDocumentStructure(self, pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractDocumentStructure", args={
            "pages_text": pages_text,
        }, mode="stream")
        return __result__
    async def ExtractEntitiesFromText(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractEntitiesFromText", args={
            "text": text,
        }, mode="stream")
        return __result__
    async def FindSectionStart(self, section_title: str,pages_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="FindSectionStart", args={
            "section_title": section_title,"pages_text": pages_text,
        }, mode="stream")
        return __result__
    async def GenerateAnswer(self, system_prompt: str,context: str,query: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateAnswer", args={
            "system_prompt": system_prompt,"context": context,"query": query,"history": history,
        }, mode="stream")
        return __result__
    async def GenerateDocDescription(self, tree_structure: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateDocDescription", args={
            "tree_structure": tree_structure,
        }, mode="stream")
        return __result__
    async def GenerateHypotheticalDocument(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateHypotheticalDocument", args={
            "query": query,
        }, mode="stream")
        return __result__
    async def GenerateNodeSummary(self, title: str,section_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateNodeSummary", args={
            "title": title,"section_text": section_text,
        }, mode="stream")
        return __result__
    async def GenerateQueryVariants(self, query: str,num_variants: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateQueryVariants", args={
            "query": query,"num_variants": num_variants,
        }, mode="stream")
        return __result__
    async def GenerateReasoningStep(self, query: str,context: str,prior_reasoning: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateReasoningStep", args={
            "query": query,"context": context,"prior_reasoning": prior_reasoning,
        }, mode="stream")
        return __result__
    async def GenerateStepBackQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateStepBackQuery", args={
            "query": query,
        }, mode="stream")
        return __result__
    async def JudgeAnswerQuality(self, query: str,prediction: str,reference: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="JudgeAnswerQuality", args={
            "query": query,"prediction": prediction,"reference": reference,
        }, mode="stream")
        return __result__
    async def JudgeRetrievalNecessity(self, query: str,knowledge_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="JudgeRetrievalNecessity", args={
            "query": query,"knowledge_description": knowledge_description,
        }, mode="stream")
        return __result__
    async def ParseTableOfContents(self, toc_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ParseTableOfContents", args={
            "toc_text": toc_text,
        }, mode="stream")
        return __result__
    async def RerankChunks(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="RerankChunks", args={
            "query": query,"passages": passages,
        }, mode="stream")
        return __result__
    async def SynthesizeDocument(self, page_analyses: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SynthesizeDocument", args={
            "page_analyses": page_analyses,
        }, mode="stream")
        return __result__
    async def TreeRetrievalStep(self, query: str,tree_structure: str,accumulated_context: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="TreeRetrievalStep", args={
            "query": query,"tree_structure": tree_structure,"accumulated_context": accumulated_context,
        }, mode="stream")
        return __result__
    async def VerifySectionPosition(self, title: str,page_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="VerifySectionPosition", args={
            "title": title,"page_text": page_text,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))