# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzePage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePage", llm_response=llm_response, mode="request")
        return typing.cast(types.PageAnalysis, __result__)

    def AnalyzeQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.QueryAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.QueryAnalysis, __result__)

    def CheckRelevance(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RelevanceJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CheckRelevance", llm_response=llm_response, mode="request")
        return typing.cast(types.RelevanceJudgment, __result__)

    def CompressRetrievedContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CompressedContext:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CompressRetrievedContext", llm_response=llm_response, mode="request")
        return typing.cast(types.CompressedContext, __result__)

    def ContinueDocumentStructure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ExtractedStructure:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ContinueDocumentStructure", llm_response=llm_response, mode="request")
        return typing.cast(types.ExtractedStructure, __result__)

    def DetectTableOfContents(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TocDetectionResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectTableOfContents", llm_response=llm_response, mode="request")
        return typing.cast(types.TocDetectionResult, __result__)

    def ExtractDocumentStructure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ExtractedStructure:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractDocumentStructure", llm_response=llm_response, mode="request")
        return typing.cast(types.ExtractedStructure, __result__)

    def ExtractEntitiesFromText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEntitiesFromText", llm_response=llm_response, mode="request")
        return typing.cast(types.PageAnalysis, __result__)

    def FindSectionStart(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> int:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FindSectionStart", llm_response=llm_response, mode="request")
        return typing.cast(int, __result__)

    def GenerateAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateAnswer", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def GenerateDocDescription(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateDocDescription", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def GenerateHypotheticalDocument(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.HypotheticalDocument:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateHypotheticalDocument", llm_response=llm_response, mode="request")
        return typing.cast(types.HypotheticalDocument, __result__)

    def GenerateNodeSummary(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateNodeSummary", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def GenerateQueryVariants(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.QueryVariants:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateQueryVariants", llm_response=llm_response, mode="request")
        return typing.cast(types.QueryVariants, __result__)

    def GenerateReasoningStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ReasoningStep:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateReasoningStep", llm_response=llm_response, mode="request")
        return typing.cast(types.ReasoningStep, __result__)

    def GenerateStepBackQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StepBackQuery:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateStepBackQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.StepBackQuery, __result__)

    def JudgeAnswerQuality(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AnswerQualityJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeAnswerQuality", llm_response=llm_response, mode="request")
        return typing.cast(types.AnswerQualityJudgment, __result__)

    def JudgeRetrievalNecessity(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RetrievalNecessityJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeRetrievalNecessity", llm_response=llm_response, mode="request")
        return typing.cast(types.RetrievalNecessityJudgment, __result__)

    def ParseTableOfContents(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TocStructure:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ParseTableOfContents", llm_response=llm_response, mode="request")
        return typing.cast(types.TocStructure, __result__)

    def RerankChunks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.RankedChunk"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RerankChunks", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.RankedChunk"], __result__)

    def SynthesizeDocument(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DocumentSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeDocument", llm_response=llm_response, mode="request")
        return typing.cast(types.DocumentSynthesis, __result__)

    def TreeRetrievalStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ToolFetchPages", "types.ToolDrillDown", "types.ToolResolvedPages"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="TreeRetrievalStep", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.ToolFetchPages", "types.ToolDrillDown", "types.ToolResolvedPages"], __result__)

    def VerifySectionPosition(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> bool:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="VerifySectionPosition", llm_response=llm_response, mode="request")
        return typing.cast(bool, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzePage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzePage", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PageAnalysis, __result__)

    def AnalyzeQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.QueryAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.QueryAnalysis, __result__)

    def CheckRelevance(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RelevanceJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CheckRelevance", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RelevanceJudgment, __result__)

    def CompressRetrievedContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CompressedContext:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CompressRetrievedContext", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CompressedContext, __result__)

    def ContinueDocumentStructure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ExtractedStructure:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ContinueDocumentStructure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ExtractedStructure, __result__)

    def DetectTableOfContents(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TocDetectionResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectTableOfContents", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TocDetectionResult, __result__)

    def ExtractDocumentStructure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ExtractedStructure:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractDocumentStructure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ExtractedStructure, __result__)

    def ExtractEntitiesFromText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PageAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEntitiesFromText", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PageAnalysis, __result__)

    def FindSectionStart(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> int:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FindSectionStart", llm_response=llm_response, mode="stream")
        return typing.cast(int, __result__)

    def GenerateAnswer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateAnswer", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def GenerateDocDescription(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateDocDescription", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def GenerateHypotheticalDocument(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.HypotheticalDocument:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateHypotheticalDocument", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.HypotheticalDocument, __result__)

    def GenerateNodeSummary(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateNodeSummary", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def GenerateQueryVariants(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.QueryVariants:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateQueryVariants", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.QueryVariants, __result__)

    def GenerateReasoningStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ReasoningStep:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateReasoningStep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ReasoningStep, __result__)

    def GenerateStepBackQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StepBackQuery:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateStepBackQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StepBackQuery, __result__)

    def JudgeAnswerQuality(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AnswerQualityJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeAnswerQuality", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AnswerQualityJudgment, __result__)

    def JudgeRetrievalNecessity(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RetrievalNecessityJudgment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeRetrievalNecessity", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RetrievalNecessityJudgment, __result__)

    def ParseTableOfContents(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TocStructure:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ParseTableOfContents", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TocStructure, __result__)

    def RerankChunks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.RankedChunk"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RerankChunks", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.RankedChunk"], __result__)

    def SynthesizeDocument(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DocumentSynthesis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeDocument", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DocumentSynthesis, __result__)

    def TreeRetrievalStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.ToolFetchPages", "stream_types.ToolDrillDown", "stream_types.ToolResolvedPages"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="TreeRetrievalStep", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.ToolFetchPages", "stream_types.ToolDrillDown", "stream_types.ToolResolvedPages"], __result__)

    def VerifySectionPosition(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> bool:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="VerifySectionPosition", llm_response=llm_response, mode="stream")
        return typing.cast(bool, __result__)

    