# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (35)
# #########################################################################

class AnswerQualityJudgment(BaseModel):
    score: typing.Optional[float] = Field(default=None, description='Answer quality score from 0.0 (completely wrong) to 1.0 (perfect)')
    reasoning: typing.Optional[str] = Field(default=None, description='Brief explanation of the score')

class AnswerabilityVerdict(BaseModel):
    answerable: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None

class CompressedContext(BaseModel):
    compressed_text: typing.Optional[str] = Field(default=None, description='The compressed context preserving only query-relevant information')

class DetectedComponent(BaseModel):
    component_id: typing.Optional[str] = Field(default=None, description='stable within-page ID: \'R1\', \'V-101\', or synthesised')
    symbol_class: typing.Optional[str] = Field(default=None, description='resistor | capacitor | valve | pump | junction | off_page_connector | ...')
    label: typing.Optional[str] = Field(default=None, description='visible printed text near the symbol')
    bbox: typing.List[int] = Field(description='[x, y, w, h] page pixel coords')
    ports: typing.List["Port"]
    properties: typing.Optional[typing.Dict[str, str]] = None

class DetectedConnection(BaseModel):
    from_component: typing.Optional[str] = None
    from_port: typing.Optional[str] = None
    to_component: typing.Optional[str] = None
    to_port: typing.Optional[str] = None
    net_label: typing.Optional[str] = Field(default=None, description='\'N5\', \'+24V\', or null for unnamed')
    wire_style: typing.Optional[str] = Field(default=None, description='solid | dashed | pneumatic | hydraulic | signal')

class DiscoveredEntity(BaseModel):
    name: typing.Optional[str] = None
    category: typing.Optional[str] = None
    value: typing.Optional[str] = None
    context: typing.Optional[str] = None

class DiscoveredTable(BaseModel):
    title: typing.Optional[str] = None
    columns: typing.List[str]
    rows: typing.List[typing.Dict[str, str]]

class DocumentSynthesis(BaseModel):
    cross_references: typing.List["SynthesisCrossReference"]
    page_clusters: typing.List["SynthesisPageCluster"]
    document_summary: typing.Optional[str] = None

class DrawingPageAnalysis(BaseModel):
    page_number: typing.Optional[int] = None
    sheet_number: typing.Optional[str] = None
    zone_grid: typing.Optional[str] = Field(default=None, description='\'A-H horizontal, 1-8 vertical\' or similar grid spec')
    domain: typing.Optional[str] = Field(default=None, description='electrical | p_and_id | mechanical | mixed')
    components: typing.List["DetectedComponent"]
    connections: typing.List["DetectedConnection"]
    off_page_connectors: typing.List["OffPageConnector"]
    title_block: typing.Optional[typing.Dict[str, str]] = None
    notes: typing.List[str]
    page_type: typing.Optional[str] = Field(default=None, description='drawing | title_page | bom | text | mixed')

class DrawingSetSynthesis(BaseModel):
    ambiguous_component_merges: typing.List["Merge"]
    narrative_cross_references: typing.List["NarrativeXref"]
    document_summary: typing.Optional[str] = None

class ExtractedSection(BaseModel):
    structure: typing.Optional[str] = Field(default=None, description='hierarchical numbering')
    title: typing.Optional[str] = Field(default=None, description='section title')
    start_page: typing.Optional[int] = Field(default=None, description='page where this section begins')

class ExtractedStructure(BaseModel):
    sections: typing.List["ExtractedSection"] = Field(description='document sections discovered from content')

class HypotheticalDocument(BaseModel):
    passage: typing.Optional[str] = Field(default=None, description='A hypothetical document passage answering the question')

class Merge(BaseModel):
    page_a: typing.Optional[int] = None
    component_a: typing.Optional[str] = None
    page_b: typing.Optional[int] = None
    component_b: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    rationale: typing.Optional[str] = None

class NarrativeXref(BaseModel):
    source_page: typing.Optional[int] = None
    target_page: typing.Optional[int] = None
    description: typing.Optional[str] = None

class OffPageConnector(BaseModel):
    tag: typing.Optional[str] = Field(default=None, description='\'/A2\', \'OPC-1\', \'to sheet 3 zone B2\'')
    bound_component: typing.Optional[str] = Field(default=None, description='on-page component_id it terminates at')
    target_hint: typing.Optional[str] = Field(default=None, description='parsed \'sheet 3, zone B2\' hint if present')

class PageAnalysis(BaseModel):
    description: typing.Optional[str] = None
    entities: typing.List["DiscoveredEntity"]
    tables: typing.List["DiscoveredTable"]
    annotations: typing.List[str]
    page_type: typing.Optional[str] = None

class Port(BaseModel):
    port_id: typing.Optional[str] = Field(default=None, description='label or index of the port')
    position: typing.Optional[typing.List[int]] = Field(default=None, description='[x, y] in page pixel coords, optional')

class QueryAnalysis(BaseModel):
    keywords: typing.List[str]
    entity_references: typing.List[str]
    intent: typing.Optional[str] = None

class QueryClassification(BaseModel):
    complexity: typing.Optional[types.QueryComplexity] = None
    query_type: typing.Optional[types.QueryType] = None
    reasoning: typing.Optional[str] = None

class QueryVariants(BaseModel):
    variants: typing.List[str] = Field(description='Alternative query formulations')

class RankedChunk(BaseModel):
    index: typing.Optional[int] = None
    score: typing.Optional[float] = None
    reasoning: typing.Optional[str] = None

class ReasoningStep(BaseModel):
    text: typing.Optional[str] = Field(default=None, description='The generated reasoning step or final answer')
    is_final: typing.Optional[bool] = Field(default=None, description='True if this is a final answer, false if more reasoning is needed')

class RelevanceJudgment(BaseModel):
    relevant: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None
    needs_clarification: typing.Optional[bool] = None
    clarifying_question: typing.Optional[str] = None
    clarifying_options: typing.Optional[typing.List[str]] = None

class RetrievalNecessityJudgment(BaseModel):
    should_retrieve: typing.Optional[bool] = Field(default=None, description='True if the query requires domain-specific knowledge retrieval')
    confidence: typing.Optional[float] = Field(default=None, description='Confidence in the judgment from 0.0 to 1.0')
    reasoning: typing.Optional[str] = Field(default=None, description='Brief explanation of why retrieval is or is not needed')

class StepBackQuery(BaseModel):
    broader_query: typing.Optional[str] = Field(default=None, description='A broader version of the original question')

class SynthesisCrossReference(BaseModel):
    source_page: typing.Optional[int] = None
    target_page: typing.Optional[int] = None
    relationship: typing.Optional[str] = None
    shared_entities: typing.List[str]

class SynthesisPageCluster(BaseModel):
    pages: typing.List[int]
    reason: typing.Optional[str] = None

class SyntheticQueries(BaseModel):
    queries: typing.List[str] = Field(description='Short questions the passage directly answers, one per facet.')

class TocDetectionResult(BaseModel):
    has_toc: typing.Optional[bool] = Field(default=None, description='whether the page contains a table of contents')
    has_page_numbers: typing.Optional[bool] = Field(default=None, description='whether the TOC entries include page numbers')

class TocEntry(BaseModel):
    structure: typing.Optional[str] = Field(default=None, description='hierarchical numbering, e.g. \'1\', \'1.1\', \'1.1.2\'')
    title: typing.Optional[str] = Field(default=None, description='section title text')
    page: typing.Optional[int] = Field(default=None, description='page number if present in TOC, null otherwise')

class TocStructure(BaseModel):
    entries: typing.List["TocEntry"] = Field(description='ordered list of TOC entries with hierarchy')

class ToolDrillDown(BaseModel):
    node_id: typing.Optional[str] = Field(default=None, description='ID of the node to explore deeper')
    reasoning: typing.Optional[str] = Field(default=None, description='why this subtree needs closer inspection')

class ToolFetchPages(BaseModel):
    pages: typing.Optional[str] = Field(default=None, description='page ranges to retrieve, e.g. \'5-7\' or \'3,8,12-15\'')
    reasoning: typing.Optional[str] = Field(default=None, description='why these pages are likely relevant to the query')

class ToolResolvedPages(BaseModel):
    pages: typing.Optional[str] = Field(default=None, description='final relevant page ranges that answer the query')
    reasoning: typing.Optional[str] = Field(default=None, description='summary of how these pages address the query')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
