# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AnswerQualityJudgment": types.AnswerQualityJudgment,
    "stream_types.AnswerQualityJudgment": stream_types.AnswerQualityJudgment,

    "types.CompressedContext": types.CompressedContext,
    "stream_types.CompressedContext": stream_types.CompressedContext,

    "types.DetectedComponent": types.DetectedComponent,
    "stream_types.DetectedComponent": stream_types.DetectedComponent,

    "types.DetectedConnection": types.DetectedConnection,
    "stream_types.DetectedConnection": stream_types.DetectedConnection,

    "types.DiscoveredEntity": types.DiscoveredEntity,
    "stream_types.DiscoveredEntity": stream_types.DiscoveredEntity,

    "types.DiscoveredTable": types.DiscoveredTable,
    "stream_types.DiscoveredTable": stream_types.DiscoveredTable,

    "types.DocumentSynthesis": types.DocumentSynthesis,
    "stream_types.DocumentSynthesis": stream_types.DocumentSynthesis,

    "types.DrawingPageAnalysis": types.DrawingPageAnalysis,
    "stream_types.DrawingPageAnalysis": stream_types.DrawingPageAnalysis,

    "types.DrawingSetSynthesis": types.DrawingSetSynthesis,
    "stream_types.DrawingSetSynthesis": stream_types.DrawingSetSynthesis,

    "types.ExtractedSection": types.ExtractedSection,
    "stream_types.ExtractedSection": stream_types.ExtractedSection,

    "types.ExtractedStructure": types.ExtractedStructure,
    "stream_types.ExtractedStructure": stream_types.ExtractedStructure,

    "types.HypotheticalDocument": types.HypotheticalDocument,
    "stream_types.HypotheticalDocument": stream_types.HypotheticalDocument,

    "types.Merge": types.Merge,
    "stream_types.Merge": stream_types.Merge,

    "types.NarrativeXref": types.NarrativeXref,
    "stream_types.NarrativeXref": stream_types.NarrativeXref,

    "types.OffPageConnector": types.OffPageConnector,
    "stream_types.OffPageConnector": stream_types.OffPageConnector,

    "types.PageAnalysis": types.PageAnalysis,
    "stream_types.PageAnalysis": stream_types.PageAnalysis,

    "types.Port": types.Port,
    "stream_types.Port": stream_types.Port,

    "types.QueryAnalysis": types.QueryAnalysis,
    "stream_types.QueryAnalysis": stream_types.QueryAnalysis,

    "types.QueryVariants": types.QueryVariants,
    "stream_types.QueryVariants": stream_types.QueryVariants,

    "types.RankedChunk": types.RankedChunk,
    "stream_types.RankedChunk": stream_types.RankedChunk,

    "types.ReasoningStep": types.ReasoningStep,
    "stream_types.ReasoningStep": stream_types.ReasoningStep,

    "types.RelevanceJudgment": types.RelevanceJudgment,
    "stream_types.RelevanceJudgment": stream_types.RelevanceJudgment,

    "types.RetrievalNecessityJudgment": types.RetrievalNecessityJudgment,
    "stream_types.RetrievalNecessityJudgment": stream_types.RetrievalNecessityJudgment,

    "types.StepBackQuery": types.StepBackQuery,
    "stream_types.StepBackQuery": stream_types.StepBackQuery,

    "types.SynthesisCrossReference": types.SynthesisCrossReference,
    "stream_types.SynthesisCrossReference": stream_types.SynthesisCrossReference,

    "types.SynthesisPageCluster": types.SynthesisPageCluster,
    "stream_types.SynthesisPageCluster": stream_types.SynthesisPageCluster,

    "types.SyntheticQueries": types.SyntheticQueries,
    "stream_types.SyntheticQueries": stream_types.SyntheticQueries,

    "types.TocDetectionResult": types.TocDetectionResult,
    "stream_types.TocDetectionResult": stream_types.TocDetectionResult,

    "types.TocEntry": types.TocEntry,
    "stream_types.TocEntry": stream_types.TocEntry,

    "types.TocStructure": types.TocStructure,
    "stream_types.TocStructure": stream_types.TocStructure,

    "types.ToolDrillDown": types.ToolDrillDown,
    "stream_types.ToolDrillDown": stream_types.ToolDrillDown,

    "types.ToolFetchPages": types.ToolFetchPages,
    "stream_types.ToolFetchPages": stream_types.ToolFetchPages,

    "types.ToolResolvedPages": types.ToolResolvedPages,
    "stream_types.ToolResolvedPages": stream_types.ToolResolvedPages,


}