# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (24)
# #########################################################################

class AnswerQualityJudgment(BaseModel):
    score: float = Field(description='Answer quality score from 0.0 (completely wrong) to 1.0 (perfect)')
    reasoning: str = Field(description='Brief explanation of the score')

class CompressedContext(BaseModel):
    compressed_text: str = Field(description='The compressed context preserving only query-relevant information')

class DiscoveredEntity(BaseModel):
    name: str
    category: str
    value: typing.Optional[str] = None
    context: str

class DiscoveredTable(BaseModel):
    title: typing.Optional[str] = None
    columns: typing.List[str]
    rows: typing.List[typing.Dict[str, str]]

class DocumentSynthesis(BaseModel):
    cross_references: typing.List["SynthesisCrossReference"]
    page_clusters: typing.List["SynthesisPageCluster"]
    document_summary: str

class ExtractedSection(BaseModel):
    structure: str = Field(description='hierarchical numbering')
    title: str = Field(description='section title')
    start_page: int = Field(description='page where this section begins')

class ExtractedStructure(BaseModel):
    sections: typing.List["ExtractedSection"] = Field(description='document sections discovered from content')

class HypotheticalDocument(BaseModel):
    passage: str = Field(description='A hypothetical document passage answering the question')

class PageAnalysis(BaseModel):
    description: str
    entities: typing.List["DiscoveredEntity"]
    tables: typing.List["DiscoveredTable"]
    annotations: typing.List[str]
    page_type: str

class QueryAnalysis(BaseModel):
    keywords: typing.List[str]
    entity_references: typing.List[str]
    intent: str
    domain_hint: typing.Optional[str] = None

class QueryVariants(BaseModel):
    variants: typing.List[str] = Field(description='Alternative query formulations')

class RankedChunk(BaseModel):
    index: int
    score: float
    reasoning: typing.Optional[str] = None

class ReasoningStep(BaseModel):
    text: str = Field(description='The generated reasoning step or final answer')
    is_final: bool = Field(description='True if this is a final answer, false if more reasoning is needed')

class RelevanceJudgment(BaseModel):
    relevant: bool
    reasoning: str
    needs_clarification: bool
    clarifying_question: typing.Optional[str] = None
    clarifying_options: typing.Optional[typing.List[str]] = None

class RetrievalNecessityJudgment(BaseModel):
    should_retrieve: bool = Field(description='True if the query requires domain-specific knowledge retrieval')
    confidence: float = Field(description='Confidence in the judgment from 0.0 to 1.0')
    reasoning: str = Field(description='Brief explanation of why retrieval is or is not needed')

class StepBackQuery(BaseModel):
    broader_query: str = Field(description='A broader version of the original question')

class SynthesisCrossReference(BaseModel):
    source_page: int
    target_page: int
    relationship: str
    shared_entities: typing.List[str]

class SynthesisPageCluster(BaseModel):
    pages: typing.List[int]
    reason: str

class TocDetectionResult(BaseModel):
    has_toc: bool = Field(description='whether the page contains a table of contents')
    has_page_numbers: bool = Field(description='whether the TOC entries include page numbers')

class TocEntry(BaseModel):
    structure: str = Field(description='hierarchical numbering, e.g. \'1\', \'1.1\', \'1.1.2\'')
    title: str = Field(description='section title text')
    page: typing.Optional[int] = Field(default=None, description='page number if present in TOC, null otherwise')

class TocStructure(BaseModel):
    entries: typing.List["TocEntry"] = Field(description='ordered list of TOC entries with hierarchy')

class ToolDrillDown(BaseModel):
    node_id: str = Field(description='ID of the node to explore deeper')
    reasoning: str = Field(description='why this subtree needs closer inspection')

class ToolFetchPages(BaseModel):
    pages: str = Field(description='page ranges to retrieve, e.g. \'5-7\' or \'3,8,12-15\'')
    reasoning: str = Field(description='why these pages are likely relevant to the query')

class ToolResolvedPages(BaseModel):
    pages: str = Field(description='final relevant page ranges that answer the query')
    reasoning: str = Field(description='summary of how these pages address the query')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
