# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (14)
# #########################################################################

class AnswerQualityJudgment(BaseModel):
    score: typing.Optional[float] = Field(default=None, description='Answer quality score from 0.0 (completely wrong) to 1.0 (perfect)')
    reasoning: typing.Optional[str] = Field(default=None, description='Brief explanation of the score')

class DetectedComponent(BaseModel):
    component_id: typing.Optional[str] = Field(default=None, description='stable within-page ID: \'R1\', \'V-101\', or synthesised')
    symbol_class: typing.Optional[str] = Field(default=None, description='resistor | capacitor | valve | pump | junction | off_page_connector | ...')
    label: typing.Optional[str] = Field(default=None, description='visible printed text near the symbol')
    bbox: typing.List[int] = Field(description='[x, y, w, h] page pixel coords')
    ports: typing.List["Port"]
    properties: typing.Optional[typing.Dict[str, str]] = None

class DetectedConnection(BaseModel):
    from_component: typing.Optional[str] = None
    from_port: typing.Optional[str] = None
    to_component: typing.Optional[str] = None
    to_port: typing.Optional[str] = None
    net_label: typing.Optional[str] = Field(default=None, description='\'N5\', \'+24V\', or null for unnamed')
    wire_style: typing.Optional[str] = Field(default=None, description='solid | dashed | pneumatic | hydraulic | signal')

class DiscoveredEntity(BaseModel):
    name: typing.Optional[str] = None
    category: typing.Optional[str] = None
    value: typing.Optional[str] = None
    context: typing.Optional[str] = None

class DiscoveredTable(BaseModel):
    title: typing.Optional[str] = None
    columns: typing.List[str]
    rows: typing.List[typing.Dict[str, str]]

class DocumentSynthesis(BaseModel):
    cross_references: typing.List["SynthesisCrossReference"]
    page_clusters: typing.List["SynthesisPageCluster"]
    document_summary: typing.Optional[str] = None

class DrawingPageAnalysis(BaseModel):
    page_number: typing.Optional[int] = None
    sheet_number: typing.Optional[str] = None
    zone_grid: typing.Optional[str] = Field(default=None, description='\'A-H horizontal, 1-8 vertical\' or similar grid spec')
    domain: typing.Optional[str] = Field(default=None, description='electrical | p_and_id | mechanical | mixed')
    components: typing.List["DetectedComponent"]
    connections: typing.List["DetectedConnection"]
    off_page_connectors: typing.List["OffPageConnector"]
    title_block: typing.Optional[typing.Dict[str, str]] = None
    notes: typing.List[str]
    page_type: typing.Optional[str] = Field(default=None, description='drawing | title_page | bom | text | mixed')

class OffPageConnector(BaseModel):
    tag: typing.Optional[str] = Field(default=None, description='\'/A2\', \'OPC-1\', \'to sheet 3 zone B2\'')
    bound_component: typing.Optional[str] = Field(default=None, description='on-page component_id it terminates at')
    target_hint: typing.Optional[str] = Field(default=None, description='parsed \'sheet 3, zone B2\' hint if present')

class PageAnalysis(BaseModel):
    description: typing.Optional[str] = None
    entities: typing.List["DiscoveredEntity"]
    tables: typing.List["DiscoveredTable"]
    annotations: typing.List[str]
    page_type: typing.Optional[str] = None

class Port(BaseModel):
    port_id: typing.Optional[str] = Field(default=None, description='label or index of the port')
    position: typing.Optional[typing.List[int]] = Field(default=None, description='[x, y] in page pixel coords, optional')

class RelevanceJudgment(BaseModel):
    relevant: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None
    needs_clarification: typing.Optional[bool] = None
    clarifying_question: typing.Optional[str] = None
    clarifying_options: typing.Optional[typing.List[str]] = None

class SynthesisCrossReference(BaseModel):
    source_page: typing.Optional[int] = None
    target_page: typing.Optional[int] = None
    relationship: typing.Optional[str] = None
    shared_entities: typing.List[str]

class SynthesisPageCluster(BaseModel):
    pages: typing.List[int]
    reason: typing.Optional[str] = None

class SyntheticQueries(BaseModel):
    queries: typing.List[str] = Field(description='Short questions the passage directly answers, one per facet.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
