# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def AnalyzeDrawingPage(self, page_image: baml_py.Image,domain_hint: str,symbol_library: str,off_page_patterns: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DrawingPageAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AnalyzeDrawingPage(page_image=page_image,domain_hint=domain_hint,symbol_library=symbol_library,off_page_patterns=off_page_patterns,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzeDrawingPage", args={
                "page_image": page_image,"domain_hint": domain_hint,"symbol_library": symbol_library,"off_page_patterns": off_page_patterns,
            })
            return typing.cast(types.DrawingPageAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def AnalyzePage(self, page_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.PageAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AnalyzePage(page_image=page_image,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzePage", args={
                "page_image": page_image,
            })
            return typing.cast(types.PageAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def AnalyzeQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.QueryAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AnalyzeQuery(query=query,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzeQuery", args={
                "query": query,
            })
            return typing.cast(types.QueryAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def CheckRelevance(self, query: str,passage: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RelevanceJudgment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.CheckRelevance(query=query,passage=passage,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="CheckRelevance", args={
                "query": query,"passage": passage,
            })
            return typing.cast(types.RelevanceJudgment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def CompressRetrievedContext(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CompressedContext:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.CompressRetrievedContext(query=query,passages=passages,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="CompressRetrievedContext", args={
                "query": query,"passages": passages,
            })
            return typing.cast(types.CompressedContext, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractEntitiesFromText(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PageAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractEntitiesFromText(text=text,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractEntitiesFromText", args={
                "text": text,
            })
            return typing.cast(types.PageAnalysis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateAnswer(self, system_prompt: str,context: str,query: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GenerateAnswer(system_prompt=system_prompt,context=context,query=query,history=history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateAnswer", args={
                "system_prompt": system_prompt,"context": context,"query": query,"history": history,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateQueryVariants(self, query: str,num_variants: int,
        baml_options: BamlCallOptions = {},
    ) -> types.QueryVariants:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GenerateQueryVariants(query=query,num_variants=num_variants,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateQueryVariants", args={
                "query": query,"num_variants": num_variants,
            })
            return typing.cast(types.QueryVariants, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateSyntheticQueries(self, passage: str,num_queries: int,
        baml_options: BamlCallOptions = {},
    ) -> types.SyntheticQueries:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GenerateSyntheticQueries(passage=passage,num_queries=num_queries,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateSyntheticQueries", args={
                "passage": passage,"num_queries": num_queries,
            })
            return typing.cast(types.SyntheticQueries, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def JudgeAnswerQuality(self, query: str,prediction: str,reference: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AnswerQualityJudgment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.JudgeAnswerQuality(query=query,prediction=prediction,reference=reference,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="JudgeAnswerQuality", args={
                "query": query,"prediction": prediction,"reference": reference,
            })
            return typing.cast(types.AnswerQualityJudgment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RerankChunks(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.RankedChunk"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RerankChunks(query=query,passages=passages,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RerankChunks", args={
                "query": query,"passages": passages,
            })
            return typing.cast(typing.List["types.RankedChunk"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def SynthesizeDocument(self, page_analyses: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DocumentSynthesis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.SynthesizeDocument(page_analyses=page_analyses,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="SynthesizeDocument", args={
                "page_analyses": page_analyses,
            })
            return typing.cast(types.DocumentSynthesis, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeDrawingPage(self, page_image: baml_py.Image,domain_hint: str,symbol_library: str,off_page_patterns: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.DrawingPageAnalysis, types.DrawingPageAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzeDrawingPage", args={
            "page_image": page_image,"domain_hint": domain_hint,"symbol_library": symbol_library,"off_page_patterns": off_page_patterns,
        })
        return baml_py.BamlSyncStream[stream_types.DrawingPageAnalysis, types.DrawingPageAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.DrawingPageAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DrawingPageAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def AnalyzePage(self, page_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PageAnalysis, types.PageAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzePage", args={
            "page_image": page_image,
        })
        return baml_py.BamlSyncStream[stream_types.PageAnalysis, types.PageAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.PageAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PageAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def AnalyzeQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.QueryAnalysis, types.QueryAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzeQuery", args={
            "query": query,
        })
        return baml_py.BamlSyncStream[stream_types.QueryAnalysis, types.QueryAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.QueryAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QueryAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CheckRelevance(self, query: str,passage: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RelevanceJudgment, types.RelevanceJudgment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="CheckRelevance", args={
            "query": query,"passage": passage,
        })
        return baml_py.BamlSyncStream[stream_types.RelevanceJudgment, types.RelevanceJudgment](
          __result__,
          lambda x: typing.cast(stream_types.RelevanceJudgment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RelevanceJudgment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CompressRetrievedContext(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CompressedContext, types.CompressedContext]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="CompressRetrievedContext", args={
            "query": query,"passages": passages,
        })
        return baml_py.BamlSyncStream[stream_types.CompressedContext, types.CompressedContext](
          __result__,
          lambda x: typing.cast(stream_types.CompressedContext, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CompressedContext, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractEntitiesFromText(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PageAnalysis, types.PageAnalysis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractEntitiesFromText", args={
            "text": text,
        })
        return baml_py.BamlSyncStream[stream_types.PageAnalysis, types.PageAnalysis](
          __result__,
          lambda x: typing.cast(stream_types.PageAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PageAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateAnswer(self, system_prompt: str,context: str,query: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateAnswer", args={
            "system_prompt": system_prompt,"context": context,"query": query,"history": history,
        })
        return baml_py.BamlSyncStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateQueryVariants(self, query: str,num_variants: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.QueryVariants, types.QueryVariants]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateQueryVariants", args={
            "query": query,"num_variants": num_variants,
        })
        return baml_py.BamlSyncStream[stream_types.QueryVariants, types.QueryVariants](
          __result__,
          lambda x: typing.cast(stream_types.QueryVariants, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QueryVariants, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateSyntheticQueries(self, passage: str,num_queries: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SyntheticQueries, types.SyntheticQueries]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateSyntheticQueries", args={
            "passage": passage,"num_queries": num_queries,
        })
        return baml_py.BamlSyncStream[stream_types.SyntheticQueries, types.SyntheticQueries](
          __result__,
          lambda x: typing.cast(stream_types.SyntheticQueries, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SyntheticQueries, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def JudgeAnswerQuality(self, query: str,prediction: str,reference: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AnswerQualityJudgment, types.AnswerQualityJudgment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="JudgeAnswerQuality", args={
            "query": query,"prediction": prediction,"reference": reference,
        })
        return baml_py.BamlSyncStream[stream_types.AnswerQualityJudgment, types.AnswerQualityJudgment](
          __result__,
          lambda x: typing.cast(stream_types.AnswerQualityJudgment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AnswerQualityJudgment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RerankChunks(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.RankedChunk"], typing.List["types.RankedChunk"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RerankChunks", args={
            "query": query,"passages": passages,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.RankedChunk"], typing.List["types.RankedChunk"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.RankedChunk"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.RankedChunk"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeDocument(self, page_analyses: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.DocumentSynthesis, types.DocumentSynthesis]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="SynthesizeDocument", args={
            "page_analyses": page_analyses,
        })
        return baml_py.BamlSyncStream[stream_types.DocumentSynthesis, types.DocumentSynthesis](
          __result__,
          lambda x: typing.cast(stream_types.DocumentSynthesis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DocumentSynthesis, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeDrawingPage(self, page_image: baml_py.Image,domain_hint: str,symbol_library: str,off_page_patterns: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeDrawingPage", args={
            "page_image": page_image,"domain_hint": domain_hint,"symbol_library": symbol_library,"off_page_patterns": off_page_patterns,
        }, mode="request")
        return __result__
    def AnalyzePage(self, page_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePage", args={
            "page_image": page_image,
        }, mode="request")
        return __result__
    def AnalyzeQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeQuery", args={
            "query": query,
        }, mode="request")
        return __result__
    def CheckRelevance(self, query: str,passage: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CheckRelevance", args={
            "query": query,"passage": passage,
        }, mode="request")
        return __result__
    def CompressRetrievedContext(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CompressRetrievedContext", args={
            "query": query,"passages": passages,
        }, mode="request")
        return __result__
    def ExtractEntitiesFromText(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractEntitiesFromText", args={
            "text": text,
        }, mode="request")
        return __result__
    def GenerateAnswer(self, system_prompt: str,context: str,query: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateAnswer", args={
            "system_prompt": system_prompt,"context": context,"query": query,"history": history,
        }, mode="request")
        return __result__
    def GenerateQueryVariants(self, query: str,num_variants: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateQueryVariants", args={
            "query": query,"num_variants": num_variants,
        }, mode="request")
        return __result__
    def GenerateSyntheticQueries(self, passage: str,num_queries: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateSyntheticQueries", args={
            "passage": passage,"num_queries": num_queries,
        }, mode="request")
        return __result__
    def JudgeAnswerQuality(self, query: str,prediction: str,reference: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="JudgeAnswerQuality", args={
            "query": query,"prediction": prediction,"reference": reference,
        }, mode="request")
        return __result__
    def RerankChunks(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RerankChunks", args={
            "query": query,"passages": passages,
        }, mode="request")
        return __result__
    def SynthesizeDocument(self, page_analyses: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeDocument", args={
            "page_analyses": page_analyses,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeDrawingPage(self, page_image: baml_py.Image,domain_hint: str,symbol_library: str,off_page_patterns: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeDrawingPage", args={
            "page_image": page_image,"domain_hint": domain_hint,"symbol_library": symbol_library,"off_page_patterns": off_page_patterns,
        }, mode="stream")
        return __result__
    def AnalyzePage(self, page_image: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzePage", args={
            "page_image": page_image,
        }, mode="stream")
        return __result__
    def AnalyzeQuery(self, query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeQuery", args={
            "query": query,
        }, mode="stream")
        return __result__
    def CheckRelevance(self, query: str,passage: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CheckRelevance", args={
            "query": query,"passage": passage,
        }, mode="stream")
        return __result__
    def CompressRetrievedContext(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CompressRetrievedContext", args={
            "query": query,"passages": passages,
        }, mode="stream")
        return __result__
    def ExtractEntitiesFromText(self, text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractEntitiesFromText", args={
            "text": text,
        }, mode="stream")
        return __result__
    def GenerateAnswer(self, system_prompt: str,context: str,query: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateAnswer", args={
            "system_prompt": system_prompt,"context": context,"query": query,"history": history,
        }, mode="stream")
        return __result__
    def GenerateQueryVariants(self, query: str,num_variants: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateQueryVariants", args={
            "query": query,"num_variants": num_variants,
        }, mode="stream")
        return __result__
    def GenerateSyntheticQueries(self, passage: str,num_queries: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateSyntheticQueries", args={
            "passage": passage,"num_queries": num_queries,
        }, mode="stream")
        return __result__
    def JudgeAnswerQuality(self, query: str,prediction: str,reference: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="JudgeAnswerQuality", args={
            "query": query,"prediction": prediction,"reference": reference,
        }, mode="stream")
        return __result__
    def RerankChunks(self, query: str,passages: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RerankChunks", args={
            "query": query,"passages": passages,
        }, mode="stream")
        return __result__
    def SynthesizeDocument(self, page_analyses: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeDocument", args={
            "page_analyses": page_analyses,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))