from typing import Protocol

from rfnry_rag.retrieval.common.models import Source, SourceStats


class BaseMetadataStore(Protocol):
    async def initialize(self) -> None: ...

    async def create_source(self, source: Source) -> None: ...

    async def get_source(self, source_id: str) -> Source | None: ...

    async def list_sources(self, knowledge_id: str | None = None) -> list[Source]: ...

    async def list_source_ids(self, knowledge_id: str | None = None) -> list[str]: ...

    async def update_source(self, source_id: str, **fields) -> None: ...

    async def delete_source(self, source_id: str) -> None: ...

    async def record_hit(self, source_id: str, chunk_id: str, grounded: bool) -> None: ...

    async def find_by_hash(self, hash_value: str, knowledge_id: str | None) -> Source | None: ...

    async def get_source_stats(self, source_id: str) -> SourceStats | None: ...

    async def save_tree_index(self, source_id: str, tree_index_json: str) -> None: ...

    async def get_tree_index(self, source_id: str) -> str | None: ...

    async def get_tree_indexes(self, source_ids: list[str]) -> dict[str, str | None]: ...

    async def shutdown(self) -> None: ...
