# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def AnalyzeContext(self, messages: str,roles: str,instructions: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AnalysisContextResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AnalyzeContext(messages=messages,roles=roles,instructions=instructions,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AnalyzeContext", args={
                "messages": messages,"roles": roles,"instructions": instructions,
            })
            return typing.cast(types.AnalysisContextResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def AnalyzeText(self, text: str,instructions: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AnalysisTextResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AnalyzeText(text=text,instructions=instructions,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AnalyzeText", args={
                "text": text,"instructions": instructions,
            })
            return typing.cast(types.AnalysisTextResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def CheckCompliance(self, text: str,reference: str,dimensions: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ComplianceJudgeResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CheckCompliance(text=text,reference=reference,dimensions=dimensions,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CheckCompliance", args={
                "text": text,"reference": reference,"dimensions": dimensions,
            })
            return typing.cast(types.ComplianceJudgeResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ClassifyText(self, text: str,categories: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ClassificationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ClassifyText(text=text,categories=categories,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ClassifyText", args={
                "text": text,"categories": categories,
            })
            return typing.cast(types.ClassificationResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ClassifyTextSets(self, text: str,category_sets: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ClassificationSetResultBAML:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ClassifyTextSets(text=text,category_sets=category_sets,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ClassifyTextSets", args={
                "text": text,"category_sets": category_sets,
            })
            return typing.cast(types.ClassificationSetResultBAML, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def JudgeOutput(self, generated: str,reference: str,dimensions: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.JudgeResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.JudgeOutput(generated=generated,reference=reference,dimensions=dimensions,context=context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="JudgeOutput", args={
                "generated": generated,"reference": reference,"dimensions": dimensions,"context": context,
            })
            return typing.cast(types.JudgeResult, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def LabelCluster(self, samples: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ClusterLabel:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.LabelCluster(samples=samples,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="LabelCluster", args={
                "samples": samples,
            })
            return typing.cast(types.ClusterLabel, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeContext(self, messages: str,roles: str,instructions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AnalysisContextResult, types.AnalysisContextResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AnalyzeContext", args={
            "messages": messages,"roles": roles,"instructions": instructions,
        })
        return baml_py.BamlStream[stream_types.AnalysisContextResult, types.AnalysisContextResult](
          __result__,
          lambda x: typing.cast(stream_types.AnalysisContextResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AnalysisContextResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def AnalyzeText(self, text: str,instructions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AnalysisTextResult, types.AnalysisTextResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AnalyzeText", args={
            "text": text,"instructions": instructions,
        })
        return baml_py.BamlStream[stream_types.AnalysisTextResult, types.AnalysisTextResult](
          __result__,
          lambda x: typing.cast(stream_types.AnalysisTextResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AnalysisTextResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CheckCompliance(self, text: str,reference: str,dimensions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ComplianceJudgeResult, types.ComplianceJudgeResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CheckCompliance", args={
            "text": text,"reference": reference,"dimensions": dimensions,
        })
        return baml_py.BamlStream[stream_types.ComplianceJudgeResult, types.ComplianceJudgeResult](
          __result__,
          lambda x: typing.cast(stream_types.ComplianceJudgeResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ComplianceJudgeResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyText(self, text: str,categories: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ClassificationResult, types.ClassificationResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ClassifyText", args={
            "text": text,"categories": categories,
        })
        return baml_py.BamlStream[stream_types.ClassificationResult, types.ClassificationResult](
          __result__,
          lambda x: typing.cast(stream_types.ClassificationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClassificationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClassifyTextSets(self, text: str,category_sets: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ClassificationSetResultBAML, types.ClassificationSetResultBAML]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ClassifyTextSets", args={
            "text": text,"category_sets": category_sets,
        })
        return baml_py.BamlStream[stream_types.ClassificationSetResultBAML, types.ClassificationSetResultBAML](
          __result__,
          lambda x: typing.cast(stream_types.ClassificationSetResultBAML, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClassificationSetResultBAML, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def JudgeOutput(self, generated: str,reference: str,dimensions: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.JudgeResult, types.JudgeResult]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="JudgeOutput", args={
            "generated": generated,"reference": reference,"dimensions": dimensions,"context": context,
        })
        return baml_py.BamlStream[stream_types.JudgeResult, types.JudgeResult](
          __result__,
          lambda x: typing.cast(stream_types.JudgeResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.JudgeResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def LabelCluster(self, samples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ClusterLabel, types.ClusterLabel]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="LabelCluster", args={
            "samples": samples,
        })
        return baml_py.BamlStream[stream_types.ClusterLabel, types.ClusterLabel](
          __result__,
          lambda x: typing.cast(stream_types.ClusterLabel, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClusterLabel, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnalyzeContext(self, messages: str,roles: str,instructions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeContext", args={
            "messages": messages,"roles": roles,"instructions": instructions,
        }, mode="request")
        return __result__
    async def AnalyzeText(self, text: str,instructions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeText", args={
            "text": text,"instructions": instructions,
        }, mode="request")
        return __result__
    async def CheckCompliance(self, text: str,reference: str,dimensions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CheckCompliance", args={
            "text": text,"reference": reference,"dimensions": dimensions,
        }, mode="request")
        return __result__
    async def ClassifyText(self, text: str,categories: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyText", args={
            "text": text,"categories": categories,
        }, mode="request")
        return __result__
    async def ClassifyTextSets(self, text: str,category_sets: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyTextSets", args={
            "text": text,"category_sets": category_sets,
        }, mode="request")
        return __result__
    async def JudgeOutput(self, generated: str,reference: str,dimensions: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="JudgeOutput", args={
            "generated": generated,"reference": reference,"dimensions": dimensions,"context": context,
        }, mode="request")
        return __result__
    async def LabelCluster(self, samples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="LabelCluster", args={
            "samples": samples,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnalyzeContext(self, messages: str,roles: str,instructions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeContext", args={
            "messages": messages,"roles": roles,"instructions": instructions,
        }, mode="stream")
        return __result__
    async def AnalyzeText(self, text: str,instructions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeText", args={
            "text": text,"instructions": instructions,
        }, mode="stream")
        return __result__
    async def CheckCompliance(self, text: str,reference: str,dimensions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CheckCompliance", args={
            "text": text,"reference": reference,"dimensions": dimensions,
        }, mode="stream")
        return __result__
    async def ClassifyText(self, text: str,categories: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyText", args={
            "text": text,"categories": categories,
        }, mode="stream")
        return __result__
    async def ClassifyTextSets(self, text: str,category_sets: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ClassifyTextSets", args={
            "text": text,"category_sets": category_sets,
        }, mode="stream")
        return __result__
    async def JudgeOutput(self, generated: str,reference: str,dimensions: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="JudgeOutput", args={
            "generated": generated,"reference": reference,"dimensions": dimensions,"context": context,
        }, mode="stream")
        return __result__
    async def LabelCluster(self, samples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="LabelCluster", args={
            "samples": samples,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))