# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AnalysisContextResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeContext", llm_response=llm_response, mode="request")
        return typing.cast(types.AnalysisContextResult, __result__)

    def AnalyzeText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AnalysisTextResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeText", llm_response=llm_response, mode="request")
        return typing.cast(types.AnalysisTextResult, __result__)

    def CheckCompliance(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ComplianceJudgeResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CheckCompliance", llm_response=llm_response, mode="request")
        return typing.cast(types.ComplianceJudgeResult, __result__)

    def ClassifyText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClassificationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyText", llm_response=llm_response, mode="request")
        return typing.cast(types.ClassificationResult, __result__)

    def ClassifyTextSets(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClassificationSetResultBAML:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyTextSets", llm_response=llm_response, mode="request")
        return typing.cast(types.ClassificationSetResultBAML, __result__)

    def JudgeOutput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.JudgeResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeOutput", llm_response=llm_response, mode="request")
        return typing.cast(types.JudgeResult, __result__)

    def LabelCluster(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClusterLabel:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="LabelCluster", llm_response=llm_response, mode="request")
        return typing.cast(types.ClusterLabel, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeContext(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AnalysisContextResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeContext", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AnalysisContextResult, __result__)

    def AnalyzeText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AnalysisTextResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeText", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AnalysisTextResult, __result__)

    def CheckCompliance(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ComplianceJudgeResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CheckCompliance", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ComplianceJudgeResult, __result__)

    def ClassifyText(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClassificationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyText", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClassificationResult, __result__)

    def ClassifyTextSets(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClassificationSetResultBAML:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyTextSets", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClassificationSetResultBAML, __result__)

    def JudgeOutput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.JudgeResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="JudgeOutput", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.JudgeResult, __result__)

    def LabelCluster(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClusterLabel:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="LabelCluster", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClusterLabel, __result__)

    