# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AnalysisContextResult": types.AnalysisContextResult,
    "stream_types.AnalysisContextResult": stream_types.AnalysisContextResult,

    "types.AnalysisTextResult": types.AnalysisTextResult,
    "stream_types.AnalysisTextResult": stream_types.AnalysisTextResult,

    "types.ClassificationResult": types.ClassificationResult,
    "stream_types.ClassificationResult": stream_types.ClassificationResult,

    "types.ClassificationSetResultBAML": types.ClassificationSetResultBAML,
    "stream_types.ClassificationSetResultBAML": stream_types.ClassificationSetResultBAML,

    "types.ClusterLabel": types.ClusterLabel,
    "stream_types.ClusterLabel": stream_types.ClusterLabel,

    "types.ComplianceJudgeResult": types.ComplianceJudgeResult,
    "stream_types.ComplianceJudgeResult": stream_types.ComplianceJudgeResult,

    "types.ComplianceViolationResult": types.ComplianceViolationResult,
    "stream_types.ComplianceViolationResult": stream_types.ComplianceViolationResult,

    "types.DimensionResultBAML": types.DimensionResultBAML,
    "stream_types.DimensionResultBAML": stream_types.DimensionResultBAML,

    "types.EntityBAML": types.EntityBAML,
    "stream_types.EntityBAML": stream_types.EntityBAML,

    "types.IntentShiftResult": types.IntentShiftResult,
    "stream_types.IntentShiftResult": stream_types.IntentShiftResult,

    "types.JudgeResult": types.JudgeResult,
    "stream_types.JudgeResult": stream_types.JudgeResult,

    "types.RetrievalHintBAML": types.RetrievalHintBAML,
    "stream_types.RetrievalHintBAML": stream_types.RetrievalHintBAML,

    "types.SetClassificationBAML": types.SetClassificationBAML,
    "stream_types.SetClassificationBAML": stream_types.SetClassificationBAML,


}