# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (13)
# #########################################################################

class AnalysisContextResult(BaseModel):
    primary_intent: str = Field(description='the main purpose or goal of this context')
    confidence: float = Field(description='0.0-1.0 confidence in the primary intent')
    summary: typing.Optional[str] = Field(default=None, description='1-2 sentence summary, or null if not requested')
    dimensions: typing.List["DimensionResultBAML"] = Field(description='scored dimensions, empty if none requested')
    entities: typing.List["EntityBAML"] = Field(description='extracted entities, empty if none requested')
    retrieval_hints: typing.List["RetrievalHintBAML"] = Field(description='suggested retrieval queries, empty if none requested')
    intent_shifts: typing.List["IntentShiftResult"] = Field(description='intent changes detected, empty if none or not tracked')
    escalation_detected: bool = Field(description='whether escalation signals were detected')
    escalation_reasoning: typing.Optional[str] = Field(default=None, description='explanation of escalation signals, null if none')
    resolution_status: str = Field(description='resolved, pending, or escalated')

class AnalysisTextResult(BaseModel):
    primary_intent: str = Field(description='the main purpose or goal of this text')
    confidence: float = Field(description='0.0-1.0 confidence in the primary intent')
    summary: typing.Optional[str] = Field(default=None, description='1-2 sentence summary, or null if not requested')
    dimensions: typing.List["DimensionResultBAML"] = Field(description='scored dimensions, empty if none requested')
    entities: typing.List["EntityBAML"] = Field(description='extracted entities, empty if none requested')
    retrieval_hints: typing.List["RetrievalHintBAML"] = Field(description='suggested retrieval queries, empty if none requested')

class ClassificationResult(BaseModel):
    category: str
    confidence: float = Field(description='0.0-1.0 certainty score')
    reasoning: str = Field(description='1-2 sentence explanation')
    runner_up: typing.Optional[str] = Field(default=None, description='second best category or null')
    runner_up_confidence: typing.Optional[float] = Field(default=None, description='0.0-1.0 or null')

class ClassificationSetResultBAML(BaseModel):
    classifications: typing.List["SetClassificationBAML"] = Field(description='one classification per category set')

class ClusterLabel(BaseModel):
    label: str = Field(description='2-5 word descriptive label for the cluster theme')

class ComplianceJudgeResult(BaseModel):
    overall_score: float = Field(description='0.0-1.0 overall compliance score')
    reasoning: str = Field(description='2-3 sentences explaining the evaluation')
    dimension_scores: typing.Dict[str, float] = Field(description='compliance score per dimension')
    violations: typing.List["ComplianceViolationResult"] = Field(description='specific breaches found, empty if fully compliant')

class ComplianceViolationResult(BaseModel):
    dimension: str = Field(description='which compliance dimension was violated')
    description: str = Field(description='specific description of the breach')
    severity: str = Field(description='high, medium, or low')
    suggestion: typing.Optional[str] = Field(default=None, description='how to fix the violation, or null')

class DimensionResultBAML(BaseModel):
    name: str = Field(description='matches the consumer-defined dimension name')
    value: str = Field(description='score value matching the consumer-defined scale')
    confidence: float = Field(description='0.0-1.0 confidence in this assessment')
    reasoning: str = Field(description='brief explanation for this score')

class EntityBAML(BaseModel):
    type: str = Field(description='matches the consumer-defined entity type name')
    value: str = Field(description='the extracted entity value')
    context: str = Field(description='surrounding text where the entity was found')

class IntentShiftResult(BaseModel):
    from_intent: str = Field(description='the previous intent before the shift')
    to_intent: str = Field(description='the new intent after the shift')
    at_message: int = Field(description='0-based index in the message list where the shift occurred')
    reasoning: str = Field(description='brief explanation of why this is an intent shift')

class JudgeResult(BaseModel):
    overall_score: float = Field(description='0.0-1.0 holistic quality score')
    reasoning: str = Field(description='2-3 sentences on strengths and weaknesses')
    dimension_scores: typing.Dict[str, float] = Field(description='score per evaluation dimension')

class RetrievalHintBAML(BaseModel):
    query: str = Field(description='suggested search query for retrieval')
    knowledge_scope: typing.Optional[str] = Field(default=None, description='which knowledge domain to search, or null')
    reasoning: str = Field(description='why this retrieval would be helpful')
    priority: float = Field(description='0.0-1.0 importance of this retrieval')

class SetClassificationBAML(BaseModel):
    set_name: str = Field(description='name of the category set this classification belongs to')
    category: str = Field(description='selected category from this set')
    confidence: float = Field(description='0.0-1.0 certainty score')
    reasoning: str = Field(description='1-2 sentence explanation')
    runner_up: typing.Optional[str] = Field(default=None, description='second best category or null')
    runner_up_confidence: typing.Optional[float] = Field(default=None, description='0.0-1.0 or null')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
